// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.PlayFabShare.Models
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ClusterAccountFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::PlayFabShare.Models.ClusterAccount>
    {


        public void Serialize(ref MessagePackWriter writer, global::PlayFabShare.Models.ClusterAccount value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            writer.Write(value.isMaster);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.MasterId, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::PlayFabShare.Models.NodeAccount>>().Serialize(ref writer, value.accounts, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.startUpPlayFabId, options);
        }

        public global::PlayFabShare.Models.ClusterAccount Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __isMaster__ = default(bool);
            var __MasterId__ = default(string);
            var __accounts__ = default(global::System.Collections.Generic.List<global::PlayFabShare.Models.NodeAccount>);
            var __startUpPlayFabId__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __isMaster__ = reader.ReadBoolean();
                        break;
                    case 1:
                        __MasterId__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __accounts__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::PlayFabShare.Models.NodeAccount>>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __startUpPlayFabId__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::PlayFabShare.Models.ClusterAccount();
            ____result.isMaster = __isMaster__;
            ____result.MasterId = __MasterId__;
            ____result.accounts = __accounts__;
            ____result.startUpPlayFabId = __startUpPlayFabId__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
