// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;
    using System.Buffers;
    using MessagePack;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(23)
            {
                { typeof(global::System.Collections.Generic.Dictionary<string, int>), 0 },
                { typeof(global::System.Collections.Generic.Dictionary<int, string>), 1 },
                { typeof(global::System.Collections.Generic.List<string>), 2 },
                { typeof(global::System.Collections.Generic.Dictionary<string, string>), 3 },
                { typeof(global::System.Collections.Generic.List<global::Share.PlayFabShare.Models.NodeAccount>), 4 },
                { typeof(global::Share.APIServer.Data.SyncPlayerDataReceipt), 5 },
                { typeof(global::Share.APIServer.Data.TempInventoryItem), 6 },
                { typeof(global::Share.APIServer.Data.Entities.GiftPack), 7 },
                { typeof(global::Share.APIServer.Data.Entities.OnlineReward), 8 },
                { typeof(global::Share.APIServer.Request.CreateMasterAccountRequest), 9 },
                { typeof(global::Share.APIServer.Request.CreateMasterAccountResponse), 10 },
                { typeof(global::Share.APIServer.Request.CreateNodeAccountRequest), 11 },
                { typeof(global::Share.APIServer.Request.CreateNodeAccountResponse), 12 },
                { typeof(global::Share.APIServer.Request.CheckCreateNodeAccountRequest), 13 },
                { typeof(global::Share.APIServer.Request.CheckCreateNodeAccountResponse), 14 },
                { typeof(global::Share.APIServer.Request.LoginRequest), 15 },
                { typeof(global::Share.APIServer.Request.LoginResponse), 16 },
                { typeof(global::Share.APIServer.Request.CommonErrorResponse), 17 },
                { typeof(global::Share.APIServer.Request.SyncDataMessage), 18 },
                { typeof(global::Share.APIServer.Request.TestRequest), 19 },
                { typeof(global::Share.APIServer.Request.TestResponse), 20 },
                { typeof(global::Share.PlayFabShare.Models.NodeAccount), 21 },
                { typeof(global::Share.PlayFabShare.Models.ClusterAccount), 22 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.DictionaryFormatter<string, int>();
                case 1: return new global::MessagePack.Formatters.DictionaryFormatter<int, string>();
                case 2: return new global::MessagePack.Formatters.ListFormatter<string>();
                case 3: return new global::MessagePack.Formatters.DictionaryFormatter<string, string>();
                case 4: return new global::MessagePack.Formatters.ListFormatter<global::Share.PlayFabShare.Models.NodeAccount>();
                case 5: return new MessagePack.Formatters.Share.APIServer.Data.SyncPlayerDataReceiptFormatter();
                case 6: return new MessagePack.Formatters.Share.APIServer.Data.TempInventoryItemFormatter();
                case 7: return new MessagePack.Formatters.Share.APIServer.Data.Entities.GiftPackFormatter();
                case 8: return new MessagePack.Formatters.Share.APIServer.Data.Entities.OnlineRewardFormatter();
                case 9: return new MessagePack.Formatters.Share.APIServer.Request.CreateMasterAccountRequestFormatter();
                case 10: return new MessagePack.Formatters.Share.APIServer.Request.CreateMasterAccountResponseFormatter();
                case 11: return new MessagePack.Formatters.Share.APIServer.Request.CreateNodeAccountRequestFormatter();
                case 12: return new MessagePack.Formatters.Share.APIServer.Request.CreateNodeAccountResponseFormatter();
                case 13: return new MessagePack.Formatters.Share.APIServer.Request.CheckCreateNodeAccountRequestFormatter();
                case 14: return new MessagePack.Formatters.Share.APIServer.Request.CheckCreateNodeAccountResponseFormatter();
                case 15: return new MessagePack.Formatters.Share.APIServer.Request.LoginRequestFormatter();
                case 16: return new MessagePack.Formatters.Share.APIServer.Request.LoginResponseFormatter();
                case 17: return new MessagePack.Formatters.Share.APIServer.Request.CommonErrorResponseFormatter();
                case 18: return new MessagePack.Formatters.Share.APIServer.Request.SyncDataMessageFormatter();
                case 19: return new MessagePack.Formatters.Share.APIServer.Request.TestRequestFormatter();
                case 20: return new MessagePack.Formatters.Share.APIServer.Request.TestResponseFormatter();
                case 21: return new MessagePack.Formatters.Share.PlayFabShare.Models.NodeAccountFormatter();
                case 22: return new MessagePack.Formatters.Share.PlayFabShare.Models.ClusterAccountFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name
