// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;
    using System.Buffers;
    using MessagePack;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(11)
            {
                { typeof(global::SourceShare.Share.NetRequest.CreateMasterAccountRequest), 0 },
                { typeof(global::SourceShare.Share.NetRequest.CreateMasterAccountResponse), 1 },
                { typeof(global::SourceShare.Share.NetRequest.CreateNodeAccountRequest), 2 },
                { typeof(global::SourceShare.Share.NetRequest.CreateNodeAccountResponse), 3 },
                { typeof(global::SourceShare.Share.NetRequest.CheckCreateNodeAccountRequest), 4 },
                { typeof(global::SourceShare.Share.NetRequest.CheckCreateNodeAccountResponse), 5 },
                { typeof(global::SourceShare.Share.NetRequest.LoginRequest), 6 },
                { typeof(global::SourceShare.Share.NetRequest.LoginResponse), 7 },
                { typeof(global::SourceShare.Share.NetRequest.CommonErrorResponse), 8 },
                { typeof(global::SourceShare.Share.NetRequest.TestRequest), 9 },
                { typeof(global::SourceShare.Share.NetRequest.TestResponse), 10 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CreateMasterAccountRequestFormatter();
                case 1: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CreateMasterAccountResponseFormatter();
                case 2: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CreateNodeAccountRequestFormatter();
                case 3: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CreateNodeAccountResponseFormatter();
                case 4: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CheckCreateNodeAccountRequestFormatter();
                case 5: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CheckCreateNodeAccountResponseFormatter();
                case 6: return new MessagePack.Formatters.SourceShare.Share.NetRequest.LoginRequestFormatter();
                case 7: return new MessagePack.Formatters.SourceShare.Share.NetRequest.LoginResponseFormatter();
                case 8: return new MessagePack.Formatters.SourceShare.Share.NetRequest.CommonErrorResponseFormatter();
                case 9: return new MessagePack.Formatters.SourceShare.Share.NetRequest.TestRequestFormatter();
                case 10: return new MessagePack.Formatters.SourceShare.Share.NetRequest.TestResponseFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name
