// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Share.PlayFabShare.Models
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class NodeAccountFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Share.PlayFabShare.Models.NodeAccount>
    {


        public void Serialize(ref MessagePackWriter writer, global::Share.PlayFabShare.Models.NodeAccount value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.serverID);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.playFabId, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.customId, options);
            writer.Write(value.level);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.avatar, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.sessionTicket, options);
        }

        public global::Share.PlayFabShare.Models.NodeAccount Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __serverID__ = default(int);
            var __playFabId__ = default(string);
            var __customId__ = default(string);
            var __level__ = default(int);
            var __avatar__ = default(string);
            var __sessionTicket__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __serverID__ = reader.ReadInt32();
                        break;
                    case 1:
                        __playFabId__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __customId__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __level__ = reader.ReadInt32();
                        break;
                    case 4:
                        __avatar__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __sessionTicket__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Share.PlayFabShare.Models.NodeAccount();
            ____result.serverID = __serverID__;
            ____result.playFabId = __playFabId__;
            ____result.customId = __customId__;
            ____result.level = __level__;
            ____result.avatar = __avatar__;
            ____result.sessionTicket = __sessionTicket__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
